import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { useNextHead } from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const head = useNextHead()

  head.add({
    name: 'google-site-verification',
    content: 'FCBvFeKjRFE5tMs3bvgAz2xS9BC6fQ-fJTaRZI2FHCs',
  })
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
